### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by strugee** [hueniverse/mailback#6]
This module needs better documentation in the README.md. Stuff like what methods are available, what options they take, etc.

**Comment by strugee** [comment]
Is there a reason this got closed? I hope I didn't come off rude; that was not the intention.

**Comment by hueniverse** [comment]
It was kinda rude. It is pretty obvious when an open source project lacks documentation, but also pretty obvious it is not the priority of the author. I think the tests are enough for those who need it to figure out what it does and how to use it.

Generally, if you care about documentation, the right approach is to raise the issue by offering to do at least some of the work...

**Comment by strugee** [comment]
Sorry, I forgot about this comment. Once again I'm sorry that I came off rude. That wasn't the intention. To me it felt kind of abrupt to have the issue closed with no explanation. Even something like "sorry, I don't have time to do this right now" would have been nice. I also tend to leave open issues for someone else to pick up, even if I don't have time to fix them myself - but I understand that's a personal preference.

If you want to stick with just the tests, you could add a sentence in the README suggesting that people look there for guidance. I for one didn't really seriously think about looking at the tests because I'm not accustomed to it. That being said:

> I think the tests are enough for those who need it to figure out what it does and how to use it.

Obviously you are free to run your project however you want, but I would strongly disagree with this. Tests are less concise than a README for communicating API, and a README can communicate lots of things that the tests never would. For example, what are some shortcomings of the module? What interfaces are documented for the purposes of semver (am I to assume that changes to _all_ behavior in the test suite would be semver-major)? How is it supposed to be used? The tests don't necessarily capture this last one because they're focused on putting the module through its paces and testing errors, edge cases, etc. rather than showing the way things are intended to be used day-to-day.

Again, that's my opinion, feel free to ignore it. But for those reasons I tend to simply skip projects without a README and I'm willing to bet there are lots of others like me.
